# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc638e226f0be92eb167d399cf8623f1d34045c8afe0dd4c5c529f32642462346ed60d1e308709f26d34b98022088bbee8dd2ff722747bcd77af344b0a51057b

test:
  secret_key_base: e494f33c50a8c79b13e71fabbe6271b44210ccc9c6307f1db50b75574de96eabb07b451e96b64990c9be090173dd46faf610b97f5cbcb9d55623d49b33ad90ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
